/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface TransportEntry {
  'owner_advance' : number,
  'date' : string,
  'bill_no' : bigint,
  'created_at' : bigint,
  'gadi_number' : string,
  'party_name' : string,
  'party_rate' : number,
  'party_advance' : number,
  'party_advance_date' : string,
  'party_advance_proof' : string,
  'to_location' : string,
  'owner_name' : string,
  'owner_rate' : number,
  'from_location' : string,
  'owner_advance_date' : string,
  'owner_advance_proof' : string,
  'comment' : string,
  'owner_paid' : boolean,
  'party_paid' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      string,
    ],
    bigint
  >,
  'updateEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      string,
      boolean,
      boolean,
    ],
    boolean
  >,
  'toggleOwnerPaid' : ActorMethod<[bigint], boolean>,
  'togglePartyPaid' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[bigint], boolean>,
  'getAllEntries' : ActorMethod<[], Array<TransportEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[bigint], [] | [TransportEntry]>,
  'getTotalCommission' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
