/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransportEntry = IDL.Record({
  'owner_advance' : IDL.Float64,
  'date' : IDL.Text,
  'bill_no' : IDL.Nat,
  'created_at' : IDL.Int,
  'gadi_number' : IDL.Text,
  'party_name' : IDL.Text,
  'party_rate' : IDL.Float64,
  'party_advance' : IDL.Float64,
  'party_advance_date' : IDL.Text,
  'party_advance_proof' : IDL.Text,
  'to_location' : IDL.Text,
  'owner_name' : IDL.Text,
  'owner_rate' : IDL.Float64,
  'from_location' : IDL.Text,
  'owner_advance_date' : IDL.Text,
  'owner_advance_proof' : IDL.Text,
  'comment' : IDL.Text,
  'owner_paid' : IDL.Bool,
  'party_paid' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'toggleOwnerPaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'togglePartyPaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(TransportEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(TransportEntry)], ['query']),
  'getTotalCommission' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransportEntry = IDL.Record({
    'owner_advance' : IDL.Float64,
    'date' : IDL.Text,
    'bill_no' : IDL.Nat,
    'created_at' : IDL.Int,
    'gadi_number' : IDL.Text,
    'party_name' : IDL.Text,
    'party_rate' : IDL.Float64,
    'party_advance' : IDL.Float64,
    'party_advance_date' : IDL.Text,
    'party_advance_proof' : IDL.Text,
    'to_location' : IDL.Text,
    'owner_name' : IDL.Text,
    'owner_rate' : IDL.Float64,
    'from_location' : IDL.Text,
    'owner_advance_date' : IDL.Text,
    'owner_advance_proof' : IDL.Text,
    'comment' : IDL.Text,
    'owner_paid' : IDL.Bool,
    'party_paid' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'toggleOwnerPaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'togglePartyPaid' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(TransportEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(TransportEntry)], ['query']),
    'getTotalCommission' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
